### PR TITLE
Add beamer options for centered title slide and footer formatting

### PR DESCRIPTION
**Pull request by johnwikman**
This PR adds options for the beamer style, such that the current style is unchanged should one not wish to have my modifications.

The options are for:

* Centered text on the title slide
* Whether to use the pdf version for the KTH lines or to use the tikz version
* What kind of content should go where in the footer

Also added a Makefile for easier testing with multiple aspect ratios.

### CODE REVIEW

**Comment by dlunde** [comment]
I think it looks great. I get the following, however, when I run `make example`:
```
$ make example
mkdir -p _build
tail --lines=+2 example.tex | cat <(echo "\documentclass[aspectratio=32]{beamer}") - > _build/example-aspect32.tex
/bin/sh: 1: Syntax error: "(" unexpected
make: *** [Makefile:19: example-aspect32.pdf] Error 2
```

**Comment by johnwikman** [comment]
Try now. It runs for me on Ubuntu 22.04 now

**Comment by dlunde** [comment]
Works now. Another thing I noticed is that `1609` should be `169`. I suggest you merge after fixing that!

**Comment by johnwikman** [comment]
Good catch. For some reason beamer seems to accept 1609 anyway, even though the documentation says 169.

**Pull request merged**
